config:
  info:
    mode: 'PROD'
    desc: 'API SERVER'

  http:
    host: 'localhost'
    port: 80

  prisma:
    DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/postgres?schema=public'
