config:
  info:
    mode: 'PROD'
    desc: 'API SERVER'

  http:
    host: 'localhost'
    port: 80

  prisma:
    DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/postgres?schema=public'

  jwt:
    secret: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.'
