config:
  info:
    mode: 'DEV'
    desc: 'API SERVER'

  http:
    host: 'localhost'
    port: 8080

  prisma:
    database_url: 'postgresql://postgres:postgres@localhost:5432/postgres?schema=public'

  jwt:
    secret: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.'
